server:
  port: 8082
vaadin:
  productionMode: false
  compatibilityMode: false
spring:
  datasource:
    url: jdbc:h2:file:./database/notificator;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password: 12345
  mail:
    host: smtp.yandex.ru
    from: dunderflute@yandex.ru
    to: abarakus@bk.ru #адрес(а) для отправки отчётов (через запятую, без пробелов)
    subject: Список пациентов #тема письма с отчетом (+[дата отчёта])
    username: dunderflute
    password: syxlqgfuuwhplcwr
    port: 465
    protocol: smtps
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
administrator:
  login: admin
  password: admin
smsc:
  sms:
    login: abarakus
    password: X33264124z!
    phone: 79168877777 #номер телефона, используемый приложением для получения сообщений
    get-url: https://smsc.ru/sys/get.php?get_answers=1&login=abarakus&psw=X33264124z%21&to_phone=79168877777&fmt=3&hour=1&cnt=1000
    interval: 3 #интервал перед отправкой вопроса о самочувствии (в минутах)
cron:
  expression:
    report: 0 0 19 ? * MON-FRI #cron-выражение планировщика отправки ежедневных отчетов
