server:
  port: 8082
vaadin:
  productionMode: false
  compatibilityMode: false
spring:
  datasource:
    url: jdbc:h2:file:./database/notificator;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: sa
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
administrator:
  login: admin
  password: admin
exolve:
  sms:
    phone: 79662985945 #номер телефона, используемый приложением для отправки сообщений
    url: https://api.exolve.ru/messaging/v1/SendSMS
    token: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJRV05sMENiTXY1SHZSV29CVUpkWjVNQURXSFVDS0NWODRlNGMzbEQtVHA0In0.eyJleHAiOjIwMDE1MjkxOTEsImlhdCI6MTY4NjE2OTE5MSwianRpIjoiYjc1NjI3YjYtZTI4OS00MjcwLTkyYzctYjExMzBkZGFjMzllIiwiaXNzIjoiaHR0cHM6Ly9zc28uZXhvbHZlLnJ1L3JlYWxtcy9FeG9sdmUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNmQ2M2UyMDUtZjczMS00MWZlLWJmMDYtZGJhNjVhMDM1OThjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZTg1NWQxMTMtNDMwNi00N2U4LWJhYjAtMTUxM2ZiM2I3NGI2Iiwic2Vzc2lvbl9zdGF0ZSI6ImY1NGFmYzgyLWZhMjMtNDYwNi05YTIwLWY4YWZhMGMyNGQ1MCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1leG9sdmUiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJleG9sdmVfYXBwIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJmNTRhZmM4Mi1mYTIzLTQ2MDYtOWEyMC1mOGFmYTBjMjRkNTAiLCJ1c2VyX3V1aWQiOiJlMTQ4NDFjYS02M2IwLTQzNzgtOGU0OC03YjAxZmQ0YmE0YjUiLCJjbGllbnRJZCI6ImU4NTVkMTEzLTQzMDYtNDdlOC1iYWIwLTE1MTNmYjNiNzRiNiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjE3Mi4yMC4yLjIxIiwiYXBpX2tleSI6dHJ1ZSwiYXBpZm9uaWNhX3NpZCI6ImU4NTVkMTEzLTQzMDYtNDdlOC1iYWIwLTE1MTNmYjNiNzRiNiIsImJpbGxpbmdfbnVtYmVyIjoiMTE5NjgwOCIsImFwaWZvbmljYV90b2tlbiI6ImF1dGJmODc4NjRjLTg3ZjAtNDNkYi04OTU5LTk5MTUxMjMzMGMwZiIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC1lODU1ZDExMy00MzA2LTQ3ZTgtYmFiMC0xNTEzZmIzYjc0YjYiLCJjdXN0b21lcl9pZCI6IjI2MTc3IiwiY2xpZW50QWRkcmVzcyI6IjE3Mi4yMC4yLjIxIn0.ZZobu5wgZc82METWyjqDCMCE92utz5qXPxtdzai7IySSbHc3OSADX7RwTVRcMt4TqWBG-MVprhnsrjXATMPVRLAtBaiZ36nL-Q0M8Prtzbs42xmZHV8LowFoWEvQV8ons4Twnp73XaFQpYYCKjwiKRvtgzYph9t-Oief1Za_Wxu1RUTeUuII9NgmQh4nAbvNjia_7yRZ3xr6-FFI4Cp-q0vopBZlMJLyW-pJgd9-6-hMqnPXRKtZaKV886fCKdNAG_cz_H246ovgqLLi1PsbEkIo_pNawS905RxL3J8DgmpbHxdjIOH5AvSO2rQUANOb9W1c2_7Mua0bE2gvzOGFDg
    interval: 1 #интервал перед отправкой вопроса о самочувствии (в минутах)